// CSV Column Mapping Constants for SafePackage API

export const CSV_COLUMNS = {
  // Order identifiers
  EXTERNAL_ID: "External ID",
  HOUSE_BILL_NUMBER: "House Bill Number",
  BARCODE: "Barcode (Tracking)",
  CONTAINER_ID: "Container ID",

  // Platform info
  PLATFORM_ID: "Platform ID",
  SELLER_ID: "Seller ID",

  // Countries
  EXPORT_COUNTRY: "Export Country (ISO3)",
  DESTINATION_COUNTRY: "Destination Country (ISO3)",

  // Carrier
  CARRIER_ID: "Carrier ID",

  // Weight
  GROSS_WEIGHT_VALUE: "Gross Weight Value",
  GROSS_WEIGHT_UNIT: "Gross Weight Unit (K/L)",

  // Shipper address
  SHIPPER_NAME: "Shipper Name",
  SHIPPER_ADDRESS_1: "Shipper Address 1",
  SHIPPER_ADDRESS_2: "Shipper Address 2",
  SHIPPER_CITY: "Shipper City",
  SHIPPER_STATE: "Shipper State",
  SHIPPER_POSTAL_CODE: "Shipper Postal Code",
  SHIPPER_COUNTRY: "Shipper Country (ISO3)",
  SHIPPER_PHONE: "Shipper Phone",
  SHIPPER_EMAIL: "Shipper Email",
  SHIPPER_IDENTIFIER_TYPE_1: "Shipper Identifier Type 1",
  SHIPPER_IDENTIFIER_VALUE_1: "Shipper Identifier Value 1",
  SHIPPER_IDENTIFIER_TYPE_2: "Shipper Identifier Type 2",
  SHIPPER_IDENTIFIER_VALUE_2: "Shipper Identifier Value 2",

  // Consignee address
  CONSIGNEE_NAME: "Consignee Name",
  CONSIGNEE_ADDRESS_1: "Consignee Address 1",
  CONSIGNEE_ADDRESS_2: "Consignee Address 2",
  CONSIGNEE_CITY: "Consignee City",
  CONSIGNEE_STATE: "Consignee State",
  CONSIGNEE_POSTAL_CODE: "Consignee Postal Code",
  CONSIGNEE_COUNTRY: "Consignee Country (ISO3)",
  CONSIGNEE_PHONE: "Consignee Phone",
  CONSIGNEE_EMAIL: "Consignee Email",
  CONSIGNEE_IDENTIFIER_TYPE_1: "Consignee Identifier Type 1",
  CONSIGNEE_IDENTIFIER_VALUE_1: "Consignee Identifier Value 1",
  CONSIGNEE_IDENTIFIER_TYPE_2: "Consignee Identifier Type 2",
  CONSIGNEE_IDENTIFIER_VALUE_2: "Consignee Identifier Value 2",

  // Product details
  PRODUCT_SKU: "Product SKU",
  PRODUCT_NAME: "Product Name (Advertised)",
  PRODUCT_DECLARED_NAME: "Product Declared Name",
  PRODUCT_DESCRIPTION: "Product Description (Full)",
  PRODUCT_URL: "Product URL",
  PRODUCT_IMAGE_1: "Product Image 1 (Base64)",
  PRODUCT_IMAGE_2: "Product Image 2 (Base64)",
  PRODUCT_IMAGE_3: "Product Image 3 (Base64)",
  PRODUCT_CATEGORIES: "Product Categories (pipe separated)",
  PRODUCT_QUANTITY: "Product Quantity",
  DECLARED_VALUE: "Declared Value (USD)",
  LIST_PRICE: "List Price (USD)",
  ORIGIN_COUNTRY: "Origin Country (ISO3)",
  HS_CODE: "HS Code",
  EAN_UPC: "EAN/UPC",
  NUMBER_OF_PIECES: "Number of Pieces",
  NORMALIZE_FLAG: "Normalize Flag (true/false)",
  MANUFACTURER_ID: "Manufacturer ID",
  MANUFACTURER_NAME: "Manufacturer Name",
  MANUFACTURER_ADDRESS: "Manufacturer Address",

  // Shipment details
  MASTER_BILL_PREFIX: "Master Bill Prefix",
  MASTER_BILL_SERIAL_NUMBER: "Master Bill Serial Number",
  ORIGINATOR_CODE: "Originator Code",
  ENTRY_TYPE: "Entry Type",
  TRANSPORT_MODE: "Transport Mode (AIR/TRUCK)",
  PORT_OF_ENTRY: "Port of Entry",
  PORT_OF_ARRIVAL: "Port of Arrival",
  PORT_OF_ORIGIN: "Port of Origin",
  CARRIER_NAME: "Carrier Name",
  CARRIER_CODE: "Carrier Code (IATA)",
  FLIGHT_VOYAGE_NUMBER: "Flight/Voyage Number",
  FIRMS_CODE: "FIRMS Code",
  SHIPPING_DATE: "Shipping Date (YYYY-MM-DD)",
  SCHEDULED_ARRIVAL_DATE: "Scheduled Arrival Date (YYYY-MM-DD)",
  TERMINAL_OPERATOR: "Terminal Operator",

  // Image URL (alternative to base64)
  PRODUCT_IMAGE_URL: "Product Image URL",
} as const;

// Column groups for organization
export const COLUMN_GROUPS = {
  ORDER_IDENTIFIERS: [
    CSV_COLUMNS.EXTERNAL_ID,
    CSV_COLUMNS.HOUSE_BILL_NUMBER,
    CSV_COLUMNS.BARCODE,
    CSV_COLUMNS.CONTAINER_ID,
  ],
  PLATFORM: [CSV_COLUMNS.PLATFORM_ID, CSV_COLUMNS.SELLER_ID],
  COUNTRIES: [CSV_COLUMNS.EXPORT_COUNTRY, CSV_COLUMNS.DESTINATION_COUNTRY],
  CARRIER: [CSV_COLUMNS.CARRIER_ID],
  WEIGHT: [CSV_COLUMNS.GROSS_WEIGHT_VALUE, CSV_COLUMNS.GROSS_WEIGHT_UNIT],
  SHIPPER: [
    CSV_COLUMNS.SHIPPER_NAME,
    CSV_COLUMNS.SHIPPER_ADDRESS_1,
    CSV_COLUMNS.SHIPPER_ADDRESS_2,
    CSV_COLUMNS.SHIPPER_CITY,
    CSV_COLUMNS.SHIPPER_STATE,
    CSV_COLUMNS.SHIPPER_POSTAL_CODE,
    CSV_COLUMNS.SHIPPER_COUNTRY,
    CSV_COLUMNS.SHIPPER_PHONE,
    CSV_COLUMNS.SHIPPER_EMAIL,
    CSV_COLUMNS.SHIPPER_IDENTIFIER_TYPE_1,
    CSV_COLUMNS.SHIPPER_IDENTIFIER_VALUE_1,
    CSV_COLUMNS.SHIPPER_IDENTIFIER_TYPE_2,
    CSV_COLUMNS.SHIPPER_IDENTIFIER_VALUE_2,
  ],
  CONSIGNEE: [
    CSV_COLUMNS.CONSIGNEE_NAME,
    CSV_COLUMNS.CONSIGNEE_ADDRESS_1,
    CSV_COLUMNS.CONSIGNEE_ADDRESS_2,
    CSV_COLUMNS.CONSIGNEE_CITY,
    CSV_COLUMNS.CONSIGNEE_STATE,
    CSV_COLUMNS.CONSIGNEE_POSTAL_CODE,
    CSV_COLUMNS.CONSIGNEE_COUNTRY,
    CSV_COLUMNS.CONSIGNEE_PHONE,
    CSV_COLUMNS.CONSIGNEE_EMAIL,
    CSV_COLUMNS.CONSIGNEE_IDENTIFIER_TYPE_1,
    CSV_COLUMNS.CONSIGNEE_IDENTIFIER_VALUE_1,
    CSV_COLUMNS.CONSIGNEE_IDENTIFIER_TYPE_2,
    CSV_COLUMNS.CONSIGNEE_IDENTIFIER_VALUE_2,
  ],
  PRODUCT: [
    CSV_COLUMNS.PRODUCT_SKU,
    CSV_COLUMNS.PRODUCT_NAME,
    CSV_COLUMNS.PRODUCT_DECLARED_NAME,
    CSV_COLUMNS.PRODUCT_DESCRIPTION,
    CSV_COLUMNS.PRODUCT_URL,
    CSV_COLUMNS.PRODUCT_IMAGE_1,
    CSV_COLUMNS.PRODUCT_IMAGE_2,
    CSV_COLUMNS.PRODUCT_IMAGE_3,
    CSV_COLUMNS.PRODUCT_CATEGORIES,
    CSV_COLUMNS.PRODUCT_QUANTITY,
    CSV_COLUMNS.PRODUCT_IMAGE_URL,
  ],
  PRICING: [CSV_COLUMNS.DECLARED_VALUE, CSV_COLUMNS.LIST_PRICE],
  CUSTOMS: [
    CSV_COLUMNS.ORIGIN_COUNTRY,
    CSV_COLUMNS.HS_CODE,
    CSV_COLUMNS.EAN_UPC,
    CSV_COLUMNS.NUMBER_OF_PIECES,
    CSV_COLUMNS.NORMALIZE_FLAG,
    CSV_COLUMNS.MANUFACTURER_ID,
    CSV_COLUMNS.MANUFACTURER_NAME,
    CSV_COLUMNS.MANUFACTURER_ADDRESS,
  ],
  SHIPMENT: [
    CSV_COLUMNS.MASTER_BILL_PREFIX,
    CSV_COLUMNS.MASTER_BILL_SERIAL_NUMBER,
    CSV_COLUMNS.ORIGINATOR_CODE,
    CSV_COLUMNS.ENTRY_TYPE,
    CSV_COLUMNS.TRANSPORT_MODE,
    CSV_COLUMNS.PORT_OF_ENTRY,
    CSV_COLUMNS.PORT_OF_ARRIVAL,
    CSV_COLUMNS.PORT_OF_ORIGIN,
    CSV_COLUMNS.CARRIER_NAME,
    CSV_COLUMNS.CARRIER_CODE,
    CSV_COLUMNS.FLIGHT_VOYAGE_NUMBER,
    CSV_COLUMNS.FIRMS_CODE,
    CSV_COLUMNS.SHIPPING_DATE,
    CSV_COLUMNS.SCHEDULED_ARRIVAL_DATE,
    CSV_COLUMNS.TERMINAL_OPERATOR,
  ],
} as const;

// Required columns that must have values
export const REQUIRED_COLUMNS = [
  CSV_COLUMNS.EXTERNAL_ID,
  CSV_COLUMNS.HOUSE_BILL_NUMBER,
  CSV_COLUMNS.BARCODE,
  CSV_COLUMNS.PLATFORM_ID,
  CSV_COLUMNS.SELLER_ID,
  CSV_COLUMNS.EXPORT_COUNTRY,
  CSV_COLUMNS.DESTINATION_COUNTRY,
  CSV_COLUMNS.GROSS_WEIGHT_VALUE,
  CSV_COLUMNS.GROSS_WEIGHT_UNIT,
  CSV_COLUMNS.SHIPPER_NAME,
  CSV_COLUMNS.SHIPPER_ADDRESS_1,
  CSV_COLUMNS.SHIPPER_CITY,
  CSV_COLUMNS.SHIPPER_STATE,
  CSV_COLUMNS.SHIPPER_POSTAL_CODE,
  CSV_COLUMNS.SHIPPER_COUNTRY,
  CSV_COLUMNS.CONSIGNEE_NAME,
  CSV_COLUMNS.CONSIGNEE_ADDRESS_1,
  CSV_COLUMNS.CONSIGNEE_CITY,
  CSV_COLUMNS.CONSIGNEE_STATE,
  CSV_COLUMNS.CONSIGNEE_POSTAL_CODE,
  CSV_COLUMNS.CONSIGNEE_COUNTRY,
  CSV_COLUMNS.PRODUCT_SKU,
  CSV_COLUMNS.PRODUCT_NAME,
  CSV_COLUMNS.PRODUCT_DESCRIPTION,
  CSV_COLUMNS.PRODUCT_URL,
  CSV_COLUMNS.PRODUCT_QUANTITY,
  CSV_COLUMNS.DECLARED_VALUE,
  CSV_COLUMNS.LIST_PRICE,
  CSV_COLUMNS.ORIGIN_COUNTRY,
] as const;

// All expected columns in order
export const ALL_COLUMNS = Object.values(CSV_COLUMNS);

// Carrier IDs
export const CARRIER_IDS = ["usps", "fedex", "ups", "dhl"] as const;

// Entry types
export const ENTRY_TYPES = ["01", "11", "86", "P"] as const;

// Transport modes
export const TRANSPORT_MODES = ["AIR", "TRUCK"] as const;
